### ISSUE TITLE
pending kernel update message persisting after reboot on EndeavourOS

### ISSUE THREAD

**Issue by Marcpil** [Antiz96/arch-update#74]
Hello,
In order to migrate from Manjaro Gnome to Archlinux Gnome, I am currently testing in VM an Endeavoursos and an archlinux installed with Archinstall and Architect in post-install. On both systems I use your Arch-update script for updates.
I notice a pending kernel update message on the Endaevoursos system which persists even after reboots. My kernel is indeed the latest (6.6.3-arch1-1). On Archlinux, this message does not appear.
Another small problem on both systems, the "enter" to Quit does not work and indicates at the bottom of the window "read only, the command is completed"
Thank you for your script and any help
![Capture d’écran du 2023-12-04 14-41-00](https://github.com/Antiz96/arch-update/assets/109863618/7df863c6-99bd-4e4a-8fda-74576adf0b3d)

**Comment by Antiz96** [comment]
Hello @Marcpil,

Thanks for the report!

Regarding the fact that the terminal indicates "read only -- the command is completed" instead of actually quitting, this is [the default behavior of `kgx`](https://gitlab.gnome.org/GNOME/console/-/issues/135#note_1451874) (also called `gnome-console`), the default Gnome terminal emulator.  
I understand why one would consider it a bug but Gnome considers it a feature :sweat_smile:

There's nothing `arch-update` can do at its level to change that behavior. If you don't like it, I'm afraid you're only option is to define another default terminal emulator for the system (which is unfortunately not so easy to do on Gnome if I remember correctly...).

As for the "pending kernel update" message that persists on EndeavourOS, `arch-update` has been primarily designed to work with "vanilla" Arch, which is were it is developed and tested.  
I know that EndeavourOS is managing boot/kernel related stuff with different tools and in a different way than Arch on some specific points, which is probably why `arch-update` behave differently on EndeavourOS than on Arch regarding the "pending kernel update" function.   

I'm still going to take some time to install an EndeavourOS environment soon to check what is triggering that behavior.
Depending on this behavior is indeed due to an EndeavourOS' specific change and  on how "hard" it is to take into consideration on my side, I'll see if I consider implementing a fix for it.

**Comment by Antiz96** [comment]
I could reproduce the issue. :)

It indeed seems specific to EndeavourOS as it appears that, when used with `systemd-boot` (which is the default bootloader for it), EndeavourOS does not copy/install the `vmlinuz*` file(s) under `/boot` like it's usually done but uses the `vmlinuz*` file(s) under `/usr/lib/modules/"kernel-version"/` instead (which explains why the script cannot find them under `/boot`, creating the false positive that results in the persistent ''pending kernel update" message).

[This comment](https://forum.endeavouros.com/t/why-no-boot/36046/4) confirms EndeavourOS is not using `/boot` by default but does not give any more details.
As stated in [this article](https://discovery.endeavouros.com/installation/systemd-boot/2022/12/) (in the "Understanding reinstall-kernels" chapter), EndeavourOS is using custom scripts to manage kernel files, entries and initramfs both for [dracut](https://gitlab.com/dalto.8/kernel-install-for-dracut) and [mkinitcpio](https://gitlab.com/dalto.8/eos-systemd-boot) when installed with `systemdboot`.  

Since `vmlinuz*` files are missing in `/boot` only on EndeavourOS with `systemd-boot` (Arch with systemd-boot and EndeavourOS with grub are fine), I suspect those scripts to be the cause.

Fortunately, this should be fairly easy to fix.  
I'll modify the script to fallback to `/usr/lib/modules/*/` if `vmlinuz*` files are not found in `/boot`.

**Comment by Antiz96** [comment]
Fixed in #75 
I'll release `v1.9.1` in a minute including the fix.

Thanks once again for the report!

**Comment by Antiz96** [comment]
https://github.com/Antiz96/arch-update/releases/tag/v1.9.1

**Comment by Marcpil** [comment]
That's ok, thanks

**Comment by thisisnotfez** [comment]
I am using EndeavorOS as well, and this issue is still persisting. Currently using 1.12.2. Kernel is 6.6.22.

**Comment by Antiz96** [comment]
> I am using EndeavorOS as well, and this issue is still persisting. Currently using 1.12.2. Kernel is 6.6.22.

Hi,

Unless EndeavourOS changed the way/path they are using to store kernels (vmlinuz) files, this issue has been fixed in #75 :thinking: 
I'm currently in vacation, I'll try to reproduce the bug when I'm back home (around the end of the week) and I'll let you know :slightly_smiling_face:

**Comment by thisisnotfez** [comment]
Did you want the whole thing, including the pending updates? Or just up until it prompts to update?

**Comment by Antiz96** [comment]
The part I'm interested in is after the updates actually. Once you launched `bash -x arch-update`, you can just perform the updates and stuff as usual (just ignore the extra text/logs). The part I'm interested starts by `+ kernel_reboot`. It is around the end  and should look something like:

```
+ kernel_reboot
+ find /boot/vmlinuz-linux
++ file /boot/vmlinuz-linux
++ sed 's/^.*version\ //'
++ awk '{print $1}'
+++ uname -r
++ grep 6.8.1-arch1-1
+ kernel_compare=6.8.1-arch1-1
+ '[' -z 6.8.1-arch1-1 ']'
++ eval_gettext 'No pending kernel update found\n'
++ gettext 'No pending kernel update found\n'
+++ envsubst --variables 'No pending kernel update found\n'
++ export PATH
++ envsubst 'No pending kernel update found\n'
+ info_msg 'No pending kernel update found\n'
+ msg='No pending kernel update found\n'
+ echo -e '\e[1m\e[32m==>\e[0m\e[1m No pending kernel update found\n\e[0m'
==> No pending kernel update found
```
But you can also provide me the entire output if it's easier for you.

**Comment by thisisnotfez** [comment]
```
+ kernel_reboot
+ find /boot/vmlinuz-linux
++ file /boot/vmlinuz-linux
++ sed 's/^.*version\ //'
++ awk '{print $1}'
+++ uname -r
++ grep 6.6.22-1-lts
+ kernel_compare=
+ '[' -z '' ']'
++ eval_gettext 'Reboot required:\nThere'\''s a pending kernel update on your system requiring a reboot to be applied\n'
++ gettext 'Reboot required:\nThere'\''s a pending kernel update on your system requiring a reboot to be applied\n'
+++ envsubst --variables 'Reboot required:\nThere'\''s a pending kernel update on your system requiring a reboot to be applied\n'
++ export PATH
++ envsubst 'Reboot required:\nThere'\''s a pending kernel update on your system requiring a reboot to be applied\n'
+ main_msg 'Reboot required:\nThere'\''s a pending kernel update on your system requiring a reboot to be applied\n'
+ msg='Reboot required:\nThere'\''s a pending kernel update on your system requiring a reboot to be applied\n'
+ echo -e '\e[1m\e[34m==>\e[0m\e[1m Reboot required:\nThere'\''s a pending kernel update on your system requiring a reboot to be applied\n\e[0m'
==> Reboot required:
There's a pending kernel update on your system requiring a reboot to be applied

++ eval_gettext 'Would you like to reboot now? [y/N]'
++ gettext 'Would you like to reboot now? [y/N]'
+++ envsubst --variables 'Would you like to reboot now? [y/N]'
++ export PATH
++ envsubst 'Would you like to reboot now? [y/N]'
+ ask_msg 'Would you like to reboot now? [y/N]'
+ msg='Would you like to reboot now? [y/N]'
++ echo -e '\e[1m\e[34m->\e[0m\e[1m Would you like to reboot now? [y/N]\e[0m '
+ read -rp '-> Would you like to reboot now? [y/N] ' answer
-> Would you like to reboot now? [y/N]
```
I hope this helps.

**Comment by Antiz96** [comment]
Thanks!

There is indeed something weird with your setup.
Since you are using the lts kernel (`6.6.22-1-lts`), you should have a `/boot/vmlinuz-linux-lts` on your system, which doesn't seem to be here for some reason.

As you can see on the second line of the output you provided me, there's only a file for the regular/non-lts kernel (`+ find /boot/vmlinuz-linux`), whereas there should be an additional one for the lts kernel, like so: `+ find /boot/vmlinuz-linux /boot/vmlinuz-linux-lts`.

Can you give me the output of this command please?

`ls -ltr /boot/ && ls -ltr /usr/lib/modules/*`

**Comment by thisisnotfez** [comment]
```
notme@not-here:~$ ls -ltr /boot/ && ls -ltr /usr/lib/modules/*
total 184908
-rw-r--r-- 1 root root 12829184 Feb 28 14:51 vmlinuz-linux
-rw------- 1 root root  9934323 Feb 28 15:52 initramfs-linux.img
-rw------- 1 root root 39947072 Feb 28 15:52 initramfs-linux-fallback.img
-rw------- 1 root root 59845503 Feb 28 16:52 initramfs-6.7.6-arch1-1.img
-rw------- 1 root root 58672941 Feb 28 16:57 initramfs-6.6.18-1-lts.img
-rw-r--r-- 1 root root  8099840 Mar 12 10:13 intel-ucode.img
/usr/lib/modules/6.6.22-1-lts:
total 19384
-rw-r--r--  1 root root 12931584 Mar 15 23:20 vmlinuz
-rw-r--r--  1 root root       10 Mar 15 23:20 pkgbase
-rw-r--r--  1 root root   243173 Mar 15 23:20 modules.order
-rw-r--r--  1 root root    71711 Mar 15 23:20 modules.builtin.modinfo
-rw-r--r--  1 root root     7882 Mar 15 23:20 modules.builtin
drwxr-xr-x 13 root root     4096 Mar 16 06:21 kernel
drwxr-xr-x 21 root root     4096 Mar 16 06:21 build
-rw-r--r--  1 root root   814745 Mar 16 06:21 modules.dep
-rw-r--r--  1 root root  1074144 Mar 16 06:21 modules.dep.bin
-rw-r--r--  1 root root  1581535 Mar 16 06:21 modules.alias
-rw-r--r--  1 root root  1552573 Mar 16 06:21 modules.alias.bin
-rw-r--r--  1 root root     2530 Mar 16 06:21 modules.softdep
-rw-r--r--  1 root root   679386 Mar 16 06:21 modules.symbols
-rw-r--r--  1 root root   830442 Mar 16 06:21 modules.symbols.bin
-rw-r--r--  1 root root     9666 Mar 16 06:21 modules.builtin.bin
-rw-r--r--  1 root root     7731 Mar 16 06:21 modules.builtin.alias.bin
-rw-r--r--  1 root root      455 Mar 16 06:21 modules.devname

/usr/lib/modules/6.8.1-arch1-1:
total 19468
-rw-r--r--  1 root root 12915200 Mar 16 10:15 vmlinuz
-rw-r--r--  1 root root        6 Mar 16 10:15 pkgbase
-rw-r--r--  1 root root   246627 Mar 16 10:15 modules.order
-rw-r--r--  1 root root    64707 Mar 16 10:15 modules.builtin.modinfo
-rw-r--r--  1 root root     6488 Mar 16 10:15 modules.builtin
drwxr-xr-x 13 root root     4096 Mar 18 10:31 kernel
drwxr-xr-x 21 root root     4096 Mar 18 10:31 build
-rw-r--r--  1 root root   836098 Mar 18 10:31 modules.dep
-rw-r--r--  1 root root  1098869 Mar 18 10:31 modules.dep.bin
-rw-r--r--  1 root root  1596839 Mar 18 10:31 modules.alias
-rw-r--r--  1 root root  1562461 Mar 18 10:31 modules.alias.bin
-rw-r--r--  1 root root     2839 Mar 18 10:31 modules.softdep
-rw-r--r--  1 root root   695636 Mar 18 10:31 modules.symbols
-rw-r--r--  1 root root   849493 Mar 18 10:31 modules.symbols.bin
-rw-r--r--  1 root root     8753 Mar 18 10:31 modules.builtin.bin
-rw-r--r--  1 root root     7492 Mar 18 10:31 modules.builtin.alias.bin
-rw-r--r--  1 root root      455 Mar 18 10:31 modules.devname
```
Here you go!

**Comment by Antiz96** [comment]
Alright, now the problem is clear :)

As you can see, kernel and initramfs files in `/boot` on your system are outdated (old kernel versions from Feb 28). 
EndeavourOS stores kernel files in `/boot` only when using grub (unlike vanilla Arch which always uses /boot), so my guess is that you switched from grub to systemd-boot recently (I'll let you confirm), leaving some old/unused kernel files in /boot.

Since `arch-update` is looking for kernel files in `/boot` first to detect pending kernel updates and you still have outdated/leftover files in here (from the time you removed grub if my assumption is correct), it creates a false positive.

**Comment by thisisnotfez** [comment]
I installed with and have kept systemd-boot since day 1. Not sure how those wires got crossed. lol. Although, new problem (for me), I have to determine if i can safely remove those files.

**Comment by Antiz96** [comment]
> I installed with and have kept systemd-boot since day 1. Not sure how those wires got crossed. lol. 

Well, that's weird indeed. Something definitely happened during 28 February's update :sweat_smile: 
I know EndeavoursOS are handling kernel related files differently than Arch but I'm not aware of every potential subtleties on their side... :shrug: 

> Although, new problem (for me), I have to determine if i can safely remove those files.

From my point of view, it should be safe to remove them as they appear unused. I'd say you can remove every files dated from Feb 28 from /boot (meaning `vmlinuz-linux` and every  `initramfs*` files). You wanna keep the `intel-ucode.img` file in there though!

Removing those outdated files will make `arch-update` fallback to `/usr/lib/modules/*` to look for kernel related files so it'll work as intended ;)

**Comment by thisisnotfez** [comment]
> Well, that's weird indeed. Something definitely happened during 28 February's update 😅 I know EndeavoursOS are handling kernel related files differently than Arch but I'm not aware of every potential subtleties on their side... 🤷

This is fair.

I'll remove them and carry on like nothing happened. Ty, again.

**Comment by Antiz96** [comment]
> Actually, since my guess about the grub switch is wrong and thus we don't have any clear explanations about how those files ended up laying in `/boot` on your side, do you mind opening a new issue if it ever happen again? It would be interesting to know if it was a one time weirdness (e.g. an issue during 28 February's update specifically on your side) or if it's something happening from time to time on EndeavourOS side.

Now that I think of it, it would be easy to make pending kernel upgrades detection more robust by telling `arch-update` to look for kernel files in **both** `/boot` and `/usr/lib/modules/*` (instead of fall-backing to the latter only if kernel files are not found in the former).
That doesn't solve the *mysterious* issue of those old files laying in your `/boot` but it would at least prevent the fault positive.

I'll implement that in a bit.

**Comment by Antiz96** [comment]
> I'll implement that in a bit.

Done in #129, it will be included in the next release.

**Comment by Antiz96** [comment]
The improvement to make the pending kernel update detection more robust to avoid false positive has been release in https://github.com/Antiz96/arch-update/releases/tag/v1.13.0 ;)
